name: aegisub
base: core18
adopt-info: aegisub
summary: Free cross-platform open source subtitle editor
description: |
 Aegisub is a free, cross-platform open source tool for creating and modifying subtitles.
 Aegisub makes it quick and easy to time subtitles to audio, and features many powerful tools for styling them, including a built-in real-time video preview.
grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  aegisub:
    plugin: dump
    source: "https://github.com/wangqr/Aegisub/archive/v3.3.1.tar.gz"
    source-type: tar
    override-build: |
      snapcraftctl build
      DEB_API="https://github.com/wangqr/Aegisub/archive/v3.3.1.tar.gz"
      DEB_URL=$(curl -w "%{url_effective}\n" -I -L -s -S "${DEB_API}" -o /dev/null)
      VERSION=$(echo "${DEB_URL}" | cut -d'/' -f6)
      snapcraftctl set-version $(echo $VERSION)
      rm $SNAPCRAFT_PART_INSTALL/usr/share/aegisub
      # Correct path to icon.
      sed -i 's|Icon=aegisub|Icon=/usr/share/aegisub/aegisub\.png|' ${SNAPCRAFT_PART_INSTALL}/usr/share/aegisub/aegisub.desktop
    build-packages:
      - curl
      - sed
    stage-packages:
      - libatomic1
      - libc++1
      - libnspr4
      - libnss3
      - libxss1
      - xdg-utils
    prime:
      - -usr/bin/xdg-open
  cleanup:
    after: [aegisub]
    plugin: nil
    build-snaps: [ gnome-3-28-1804 ]
    override-prime: |
        set -eux
        cd /snap/gnome-3-28-1804/current
        find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/{} \;

apps:
  aegisub:
    extensions: [gnome-3-28]
    command: usr/share/aegisub/Aegisub --no-sandbox
    autostart: aegisub.desktop
    desktop: usr/share/applications/aegis.desktop
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to
      # ensure libappindicator has readable resources
      TMPDIR: $XDG_RUNTIME_DIR
      # Coerce XDG_CURRENT_DESKTOP to Unity so that App Indicators
      # are used and do not fall back to Notification Area applets
      # or disappear completely.
      XDG_CURRENT_DESKTOP: Unity
      # Fallback to XWayland if running in a Wayland session.
      DISABLE_WAYLAND: 1
    plugs:
      - browser-support
      - camera
      - home
      - mount-observe
      - network
      - network-observe
      - opengl
      - process-control
      - pulseaudio
      - removable-media
      - screen-inhibit-control
      - system-observe
      - unity7
